### ISSUE TITLE
Pas optimisé

### ISSUE THREAD

**Issue by a-leblond** [Rahotop/Carl#1]
L'algorithme est malheureusement peu optimisé et les résultats sont mauvais.

Une amélioration est-elle prévue d'ici peu ou dois-je me tourner vers des solutions plus fiables ?

**Comment by Rahotop** [comment]
Reste calme quand même

**Comment by a-leblond** [comment]
Je vais voir pour faire une PR si j'ai le temps, j'ai corrigé certaines parties de ton code mais c'est encore perfectible

**Comment by Rahotop** [comment]
Fork et fais tes changements comme tu veux, dans un mois on regarde laquelle des deux branches est la meilleure :3

**Comment by a-leblond** [comment]
J'aurai 1000 stars, Jin-Kao en contributeur et ton diplôme sera à mon nom 🥇

**Comment by Rahotop** [comment]
Tu parles beaucoup, mais tu fork pas des masses :thinking:

**Comment by a-leblond** [comment]
Prepare yourself 🥇
